export const commandMap = {
  getRecipe: ["recipe", "get"],
  getRecipeCluster: ["recipe", "variants"],
  getRecipeClusterV2: ["recipe", "variants-v2"],
  search: ["search", "recipes"],
  searchStripe: ["search", "stripe"],
  searchIngredients: ["search", "ingredients"],
  listCreatedRecipes: ["created", "list"],
  createCreatedRecipe: ["created", "create"],
  getCreatedRecipe: ["created", "get"],
  patchCreatedRecipe: ["created", "update"],
  deleteCreatedRecipe: ["created", "delete"],
  getPublicCreatedRecipe: ["created", "public-get"],
  addBookmark: ["organize", "bookmark", "add"],
  removeBookmark: ["organize", "bookmark", "remove"],
  listCustomLists: ["organize", "custom-list", "list"],
  createCustomList: ["organize", "custom-list", "create"],
  getCustomList: ["organize", "custom-list", "get"],
  updateCustomList: ["organize", "custom-list", "update"],
  deleteCustomList: ["organize", "custom-list", "delete"],
  removeRecipeFromCustomList: ["organize", "custom-list", "remove-recipe"],
  listManagedLists: ["organize", "managed-list", "list"],
  saveManagedList: ["organize", "managed-list", "save"],
  removeManagedList: ["organize", "managed-list", "remove"],
  moveRecipe: ["organize", "move-recipe"],
  shareCustomList: ["organize", "shared-list", "share"],
  getSharedList: ["organize", "shared-list", "get"],
  revokeSharedList: ["organize", "shared-list", "revoke"],
  getPlanningWeek: ["planning", "week"],
  addRecipesToDay: ["planning", "add"],
  getPlanningDay: ["planning", "day"],
  removePlanningDay: ["planning", "clear-day"],
  removeRecipeFromDay: ["planning", "remove-recipe"],
  movePlannedRecipe: ["planning", "move"],
  getShoppingList: ["shopping", "show"],
  clearShoppingList: ["shopping", "clear"],
  addRecipesToShoppingList: ["shopping", "recipe", "add"],
  removeRecipesFromShoppingList: ["shopping", "recipe", "remove"],
  editIngredientOwnership: ["shopping", "ingredient", "ownership"],
  addAdditionalShoppingItems: ["shopping", "item", "add"],
  editAdditionalShoppingItems: ["shopping", "item", "edit"],
  editAdditionalItemOwnership: ["shopping", "item", "ownership"],
  removeAdditionalShoppingItems: ["shopping", "item", "remove"],
  createRecipeNote: ["note", "create"],
  getRecipeNote: ["note", "get"],
  updateRecipeNote: ["note", "update"],
  deleteRecipeNote: ["note", "delete"],
  getAggregatedRecipeRating: ["rating", "get"],
  setUserRecipeRating: ["rating", "set"],
  getCommunityProfile: ["profile", "get"],
  getLocalizedCommunityProfile: ["profile", "get-localized"],
  updateCommunityProfile: ["profile", "update"],
  listSubscriptions: ["subscription", "list"],
  getDeviceVersions: ["device", "versions"],
  linkConnectedDevice: ["device", "link"],
  unlinkConnectedDevice: ["device", "unlink"],
  bootstrapCollectionFeed: ["feed", "bootstrap"],
  getCollectionFeed: ["feed", "list"],
  getCollectionFeedPage: ["feed", "page"]
};
